import { useState } from 'react'

// ─── CREDENTIALS REVEAL MODAL (Chunk 30) ────────────────────────────────────
// Two-step gate to prevent directors from accidentally closing without saving.
//
// Step 1 — credentials shown with copy buttons. Primary action: "I've saved it →"
// Step 2 — confirmation prompt. Close button DISABLED until checkbox is ticked.
//
// Defenses against accidental dismissal:
//   - No [✕] icon during reveal
//   - Outside-click does NOTHING
//   - Esc key does NOTHING
//
// Pattern is identical to AWS IAM "show secret access key" flow.
//
// Props:
//   email: string — agent's email
//   password: string — the plaintext password (shown once, then gone)
//   agentName: string — for the success message
//   wasAutoGenerated: boolean — affects copy ("we generated" vs "you set")
//   actionLabel: 'created' | 'reset' — affects header copy
//   onClose: () => void — called only after user passes both gates

export default function CredentialsRevealModal({
  email, password, agentName,
  wasAutoGenerated = false,
  actionLabel = 'created',
  onClose,
}) {
  const [step, setStep] = useState(1)
  const [emailCopied, setEmailCopied] = useState(false)
  const [passwordCopied, setPasswordCopied] = useState(false)
  const [bothCopied, setBothCopied] = useState(false)
  const [confirmed, setConfirmed] = useState(false)
  const [showPassword, setShowPassword] = useState(false)

  function copy(text, setter) {
    navigator.clipboard.writeText(text).then(() => {
      setter(true)
      setTimeout(() => setter(false), 2000)
    })
  }

  return (
    <div style={{
      position: 'fixed', inset: 0,
      background: 'rgba(20, 19, 15, 0.6)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 1000, padding: 16,
    }}>
      {/* No onClick handler on the overlay — outside clicks must NOT dismiss */}
      <div style={{
        background: '#fff', borderRadius: 14,
        width: '100%', maxWidth: 480,
        overflow: 'hidden',
      }}>

        {step === 1 ? (
          // ─── STEP 1: CREDENTIALS REVEALED ──────────────────────────────
          <>
            <div style={{
              padding: '22px 24px 16px',
              borderBottom: '0.5px solid #f5f3ef',
              display: 'flex', alignItems: 'center', gap: 12,
            }}>
              <div style={{
                width: 36, height: 36, borderRadius: '50%',
                background: '#dcfce7', display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <span style={{ color: '#16a34a', fontSize: 20, fontWeight: 700 }}>✓</span>
              </div>
              <div>
                <div style={{ fontSize: 15, fontWeight: 600, color: '#14130f' }}>
                  Agent {actionLabel === 'reset' ? 'password reset' : 'created'}
                </div>
                <div style={{ fontSize: 11, color: '#9a958c', marginTop: 2 }}>
                  Save these credentials before closing this window
                </div>
              </div>
            </div>

            <div style={{ padding: '20px 24px' }}>
              <div style={{ fontSize: 13, color: '#4a4742', marginBottom: 14, lineHeight: 1.5 }}>
                <strong style={{ color: '#14130f' }}>{agentName}</strong> can now log in with:
              </div>

              {/* Email */}
              <div style={{ marginBottom: 12 }}>
                <div style={{ fontSize: 10, fontWeight: 600, color: '#9a958c', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: 6 }}>Email</div>
                <div style={{ display: 'flex', gap: 6 }}>
                  <div style={{
                    flex: 1, padding: '10px 12px',
                    background: '#faf9f7', border: '0.5px solid #dcd8d0', borderRadius: 8,
                    fontSize: 13, color: '#14130f', fontFamily: 'ui-monospace, Menlo, monospace',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  }}>{email}</div>
                  <button onClick={() => copy(email, setEmailCopied)} style={copyBtnStyle(emailCopied)}>
                    {emailCopied ? '✓ Copied' : 'Copy'}
                  </button>
                </div>
              </div>

              {/* Password */}
              <div style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 10, fontWeight: 600, color: '#9a958c', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: 6 }}>
                  Password {wasAutoGenerated && <span style={{ fontWeight: 400, textTransform: 'none', letterSpacing: 0, color: '#534ab7' }}>· auto-generated</span>}
                </div>
                <div style={{ display: 'flex', gap: 6 }}>
                  <div style={{
                    flex: 1, padding: '10px 12px',
                    background: '#faf9f7', border: '0.5px solid #dcd8d0', borderRadius: 8,
                    fontSize: 13, color: '#14130f', fontFamily: 'ui-monospace, Menlo, monospace',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                    letterSpacing: showPassword ? 'normal' : '2px',
                  }}>{showPassword ? password : '•'.repeat(password.length)}</div>
                  <button onClick={() => setShowPassword(!showPassword)} style={{
                    padding: '0 10px', border: '0.5px solid #dcd8d0', borderRadius: 8,
                    background: '#fff', color: '#6e6a63', cursor: 'pointer', fontSize: 12,
                  }}>{showPassword ? 'Hide' : 'Show'}</button>
                  <button onClick={() => copy(password, setPasswordCopied)} style={copyBtnStyle(passwordCopied)}>
                    {passwordCopied ? '✓ Copied' : 'Copy'}
                  </button>
                </div>
              </div>

              {/* Warning */}
              <div style={{
                background: '#fef9ef', border: '0.5px solid #f5e6c0', borderRadius: 8,
                padding: '10px 12px', fontSize: 11, color: '#92400e', lineHeight: 1.5,
                marginBottom: 16,
              }}>
                ⚠ This password will not be shown again. Copy it now or hand it to {agentName} directly.
              </div>

              {/* Footer buttons */}
              <div style={{ display: 'flex', gap: 8 }}>
                <button onClick={() => {
                  copy(`Email: ${email}\nPassword: ${password}`, setBothCopied)
                }} style={{
                  flex: 1, padding: '11px 14px',
                  background: '#fff', border: '0.5px solid #dcd8d0', borderRadius: 8,
                  fontSize: 13, fontWeight: 500, color: '#4a4742', cursor: 'pointer',
                }}>
                  {bothCopied ? '✓ Both copied' : 'Copy both'}
                </button>
                <button onClick={() => setStep(2)} style={{
                  flex: 2, padding: '11px 18px',
                  background: '#14134a', border: 'none', borderRadius: 8,
                  fontSize: 13, fontWeight: 500, color: '#fff', cursor: 'pointer',
                }}>
                  I've saved it →
                </button>
              </div>
            </div>
          </>
        ) : (
          // ─── STEP 2: CONFIRMATION GATE ─────────────────────────────────
          <>
            <div style={{ padding: '22px 24px 16px', borderBottom: '0.5px solid #f5f3ef' }}>
              <div style={{ fontSize: 15, fontWeight: 600, color: '#14130f' }}>
                Are you sure you've saved the password?
              </div>
              <div style={{ fontSize: 12, color: '#9a958c', marginTop: 4, lineHeight: 1.5 }}>
                Once you close this, the password cannot be retrieved. You'll have to reset it for {agentName} if you lose it.
              </div>
            </div>

            <div style={{ padding: '20px 24px' }}>
              <label style={{
                display: 'flex', alignItems: 'flex-start', gap: 10,
                cursor: 'pointer', userSelect: 'none', marginBottom: 16,
              }}>
                <input
                  type="checkbox"
                  checked={confirmed}
                  onChange={e => setConfirmed(e.target.checked)}
                  style={{ marginTop: 2, accentColor: '#534ab7', flexShrink: 0 }}
                />
                <span style={{ fontSize: 13, color: '#14130f', lineHeight: 1.5 }}>
                  I confirm I have saved or shared the password with {agentName}.
                </span>
              </label>

              <div style={{ display: 'flex', gap: 8 }}>
                <button onClick={() => setStep(1)} style={{
                  flex: 1, padding: '11px 14px',
                  background: '#fff', border: '0.5px solid #dcd8d0', borderRadius: 8,
                  fontSize: 13, fontWeight: 500, color: '#4a4742', cursor: 'pointer',
                }}>
                  ← Go back
                </button>
                <button
                  disabled={!confirmed}
                  onClick={() => onClose && onClose()}
                  style={{
                    flex: 2, padding: '11px 18px',
                    background: confirmed ? '#14134a' : '#dcd8d0',
                    border: 'none', borderRadius: 8,
                    fontSize: 13, fontWeight: 500, color: '#fff',
                    cursor: confirmed ? 'pointer' : 'not-allowed',
                    opacity: confirmed ? 1 : 0.6,
                  }}>
                  Close window
                </button>
              </div>
            </div>
          </>
        )}

      </div>
    </div>
  )
}

function copyBtnStyle(copied) {
  return {
    padding: '0 14px',
    border: copied ? '0.5px solid #16a34a' : '0.5px solid #dcd8d0',
    borderRadius: 8,
    background: copied ? '#dcfce7' : '#14134a',
    color: copied ? '#16a34a' : '#fff',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    minWidth: 72,
    transition: 'all 0.15s',
  }
}